image: continuumio/miniconda:latest

before_script:
  - conda update -y --all
  - conda install -c omnia openpathsampling
  - conda uninstall openpathsampling
  - git clone https://github.com/openpathsampling/openpathsampling.git
  - cd openpathsampling && pip install -e . && cd ..
  - conda install -c omnia ipynbtest

test:
  script:
      - NOTEBOOKS=`python devtools/select_notebooks.py --skip-file devtools/skip`
      - echo $NOTEBOOKS
      - source ./devtools/prepare.sh $NOTEBOOKS
      - echo "hypothetical test"
      #- for ipynb in *ipynb; do; ipynbtest.py $ipynb; done
