image: continuumio/miniconda:latest

before_script:
  - bash ./devtools/conda_ops_dev_install.sh
  - conda install -y curl
  - conda install -y -c conda-forge unzip
  - conda update -y --all
  - conda install -y -c omnia ipynbtest

test:
  script:
      - NOTEBOOKS=`python devtools/select_notebooks.py --skip-file devtools/skip`
      - echo $NOTEBOOKS
      - source ./devtools/prepare.sh $NOTEBOOKS
      #- for ipynb in $NOTEBOOKS; do ipynbtest.py ${ipynb}.ipynb; done
