image: continuumio/miniconda:latest

before_script:
  - export PYTHONUNBUFFERED=true
  - conda update -y --quiet -n base conda
  # curl and unzip are used to download figshare files
  - conda install -y -q -c conda-forge curl unzip
  - conda install -y -q matplotlib
  #- conda config --add channels conda-forge
  - curl -OLk https://raw.githubusercontent.com/openpathsampling/openpathsampling/master/devtools/conda_ops_dev_install.sh
  - bash ./conda_ops_dev_install.sh
  - DEVTOOLS_DIR="openpathsampling/devtools"
  - PKGS=`python ${DEVTOOLS_DIR}/install_recipe_requirements.py --dry ${DEVTOOLS_DIR}/conda-recipe/meta.yaml`
  - echo $PKGS
  - python ${DEVTOOLS_DIR}/install_recipe_requirements.py --dry ${DEVTOOLS_DIR}/conda-recipe/meta.yaml
  - conda install -y -q -c omnia ipynbtest
  - conda list

test:
  script:
    #- export MPLBACKEND=PS
    - NOTEBOOKS=`python devtools/select_notebooks.py --skip-file devtools/skip`
    # if you only want to test one notebook
    # - NOTEBOOKS="my_notebook_name"  # without the .ipynb extension!
    - source ./devtools/run_tests.sh $NOTEBOOKS
