image: continuumio/miniconda:latest

before_script:
  - export PYTHONUNBUFFERED=true
  - conda update -y --quiet -n base conda
  #- conda config --add channels conda-forge
  - bash ./devtools/conda_ops_dev_install.sh
  # curl and unzip are used to download figshare files
  - conda install -y --quiet curl
  - conda install -y --quiet -c conda-forge unzip
  - conda install -y --quiet -c omnia ipynbtest
  - conda update -y --quiet --all
  - conda list

test:
  script:
    #- export MPLBACKEND=PS
    - NOTEBOOKS=`python devtools/select_notebooks.py --skip-file devtools/skip`
    # if you only want to test one notebook
    # - NOTEBOOKS="my_notebook_name"  # without the .ipynb extension!
    - source ./devtools/run_tests.sh $NOTEBOOKS
