image: continuumio/miniconda:latest

before_script:
  - export PYTHONUNBUFFERED=true
  - conda update -y -q -n base conda
  # curl and unzip are used to download figshare files
  - conda install -y -q -c conda-forge curl unzip
  - conda install -y -q -c conda-forge matplotlib
  - conda install -y -q -c omnia ipynbtest
  - curl -OLk https://raw.githubusercontent.com/openpathsampling/openpathsampling/master/devtools/conda_ops_dev_install.sh
  - source ./conda_ops_dev_install.sh dwhswenson py37
  - conda list

test:
  script:
    #- export MPLBACKEND=PS
    - NOTEBOOKS=`python devtools/select_notebooks.py --skip-file devtools/skip`
    # if you only want to test one notebook
    # - NOTEBOOKS="my_notebook_name"  # without the .ipynb extension!
    - source ./devtools/run_tests.sh $NOTEBOOKS
