before_install:
  - source devtools/install_conda.sh
  - export PYTHONUNBUFFERED=true
  - conda update -y --quiet -n base conda
  - conda install -y --quiet ipython jupyter jupyter_client matplotlib
  - conda update -y --quiet --all
  - conda list


script:
  # works when MPLBACKEND is not set
  - ipython --version
  - ipython -c "import matplotlib.pyplot as plt"
  - ipython -c "import has_mpl"

  # works with ipython 5.5 and MPLBACKEND set
  - conda install -y --quiet ipython==5.5
  - export MPLBACKEND=PS
  - ipython -c "import matplotlib.pyplot as plt"
  - ipython -c "import has_mpl"

  # fails with ipython 5.6 and MPLBACKEND set
  - conda install -y --quiet ipython==5.6
  - ipython -c "import matplotlib.pyplot as plt"
  - ipython -c "import has_mpl"
