#sudo: required

#services: docker

before_install:
  - source devtools/install_conda.sh
  - export PYTHONUNBUFFERED=true
  - conda update -y --quiet -n base conda
  #- conda config --add channels conda-forge
  - bash ./devtools/conda_ops_dev_install.sh
  # curl and unzip are used to download figshare files
  - conda install -y --quiet curl
  - conda install -y --quiet -c conda-forge unzip
  - conda update -y --quiet --all
  - conda install -y --quiet -c omnia ipynbtest
  - conda install -y --quiet ipython==5.6
  - conda list


script:
  - export MPLBACKEND=PS
  - NOTEBOOKS=`python devtools/select_notebooks.py --skip-file devtools/skip`
  # if you only want to test one notebook
  # - NOTEBOOKS="my_notebook_name"  # without the .ipynb extension!
  - NOTEBOOKS="minimal"
  - source ./devtools/run_tests.sh $NOTEBOOKS
